# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:

env_files:
  github_token: /root/projects/keys/main

builds:
  -
    binary: wza
    id: wza
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - openbsd
      - netbsd
      - solaris
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64
      - mips64

release:
  draft: false

archives:
  -
    id: "wza"
    builds: ['wza']
    format: tar.gz
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"

    files:
      - LICENSE
      - NOTICE

nfpms:
  -
    id: "wza"
    builds: ['wza']
    formats:
      - deb
      - rpm
    vendor: "Eltaline <eltaline.ou@gmail.com>"
    homepage: "https://elta.ee/"
    maintainer: "Andrey Kuvshinov <syslinux@protonmail.com>"
    description: "Files in Bolt archiver. Used with wZD Server"
    license: "Apache 2.0"
    file_name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"

    bindir: /usr/bin

    empty_folders:
      - /usr/share/wza

    contents:
      - src: "LICENSE"
        dst: "/usr/share/wza/LICENSE"

      - src: "NOTICE"
        dst: "/usr/share/wza/NOTICE"

scoop:

  commit_author:
    name: "Andrey Kuvshinov"
    email: syslinux@protonmail.com
  homepage: "https://elta.ee/"
  license: Apache 2.0

brews:
 -
   commit_author:
     name: "Andrey Kuvshinov"
     email: syslinux@protonmail.com
   homepage: "https://elta.ee/"
   goarm: 7

snapshot:
  name_template: "{{.Version}}-master"
changelog:
  sort: asc
  filters:
    exclude:
    - README
    - OPTIONS
    - Readme
    - Options
    - Image
    - Script
    - Typo
    - "via upload"
    - goreleaser
