# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:

env_files:
  github_token: /root/projects/keys/main

builds:
  -
    binary: wza
    id: wza
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - openbsd
      - netbsd
      - solaris
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64
      - mips64

release:
  draft: false

archives:
  -
    id: "wza"
    builds: ['wza']
    format: tar.gz
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"

    files:
      - LICENSE

nfpms:
  -
    id: "wza"
    builds: ['wza']
    formats:
      - deb
      - rpm
    vendor: "Eltaline"
    homepage: "https://wzd.dev/"
    maintainer: "Andrey Kuvshinov <dev@wzd.dev>"
    description: "Files in Bolt archiver. Used with wZD Server"
    license: "BSD-3 Clause"
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"

    bindir: /usr/bin

    empty_folders:
      - /usr/share/wza

    files:
      "LICENSE": "/usr/share/wza/LICENSE"

scoop:

  commit_author:
    name: "Andrey Kuvshinov"
    email: dev@wzd.dev
  homepage: "https://wzd.dev/"
  license: BSD-3 Clause

brews:
 -
   commit_author:
     name: "Andrey Kuvshinov"
     email: dev@wzd.dev
   homepage: "https://wzd.dev/"
   goarm: 7

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Version}}-experimental"
changelog:
  sort: asc
  filters:
    exclude:
    - README
    - OPTIONS
    - Readme
    - Options
    - Image
    - Script
    - Typo
    - "via upload"
    - goreleaser
